/**
 * 会话列表管理 Hook
 * 管理会话列表状态和当前活跃会话，提供会话切换、创建、删除、重命名、摘要生成等操作
 */

import { useCallback, useState } from 'react'

import {
  createSession as storeCreateSession,
  deleteSession as storeDeleteSession,
  generateSessionSummary,
  getAllSessions,
  updateSessionFields,
  updateSessionTitle,
} from '@/ai/storage/session-store'
import type { Session } from '@/ai/storage/types'

/**
 * useSessionList 状态和操作接口
 */
export type UseSessionListState = {
  /** 所有会话列表 */
  sessions: Session[]
  /** 当前活跃会话 ID */
  activeSessionId: number | null
  /** 加载中 */
  isLoading: boolean

  /** 切换活跃会话 */
  switchSession: (id: number) => void
  /** 创建新会话并设为活跃，同时对旧会话异步触发摘要生成 */
  createSession: (title?: string) => Promise<Session>
  /** 删除会话 */
  deleteSession: (id: number) => Promise<void>
  /** 加载今日最后会话，无会话则自动创建 */
  loadTodayLastSession: () => Promise<void>
  /** 重命名会话标题，标记 titleAutoGenerated=false */
  renameSession: (id: number, newTitle: string) => Promise<void>
  /** 异步触发摘要生成，完成后更新 sessions 状态 */
  generateSummary: (id: number) => void
}

/**
 * 会话列表管理 Hook
 */
export const useSessionList = (): UseSessionListState => {
  const [sessions, setSessions] = useState<Session[]>([])
  const [activeSessionId, setActiveSessionId] = useState<number | null>(null)
  const [isLoading, setIsLoading] = useState(false)

  const switchSession = useCallback((id: number) => {
    setActiveSessionId(id)
  }, [])

  const handleCreateSession = useCallback(
    async (title?: string) => {
      const oldSessionId = activeSessionId
      const session = await storeCreateSession(title)
      setSessions((prev) => [session, ...prev])
      setActiveSessionId(session.id)

      // 对旧会话异步触发摘要生成
      if (oldSessionId !== null) {
        const oldSession = sessions.find((s) => s.id === oldSessionId)
        if (oldSession && !oldSession.summaryGenerated) {
          // 异步执行，不 await
          generateSessionSummary(
            oldSessionId,
            oldSession.title,
            oldSession.titleAutoGenerated
          )
            .then((result) => {
              setSessions((prev) =>
                prev.map((s) =>
                  s.id === oldSessionId
                    ? {
                        ...s,
                        summary: result.summary,
                        summaryGenerated: true,
                        ...(result.title ? { title: result.title } : {}),
                      }
                    : s
                )
              )
            })
            .catch(() => {
              // 摘要生成失败，不自动重试
            })
        }
      }

      return session
    },
    [activeSessionId, sessions]
  )

  const handleDeleteSession = useCallback(
    async (id: number) => {
      await storeDeleteSession(id)
      setSessions((prev) => prev.filter((s) => s.id !== id))

      // 如果删除的是活跃会话，切换到列表中第一个
      if (activeSessionId === id) {
        setSessions((prev) => {
          if (prev.length > 0) {
            setActiveSessionId(prev[0].id)
          } else {
            setActiveSessionId(null)
          }
          return prev
        })
      }
    },
    [activeSessionId]
  )

  const loadTodayLastSession = useCallback(async () => {
    setIsLoading(true)
    try {
      const allSessions = await getAllSessions()
      setSessions(allSessions)

      // 获取今天的日期字符串（本地时间）
      const today = new Date()
      const todayStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`

      // 找到今天创建的最后一个会话（列表已按 createdAt 倒序）
      const todaySession = allSessions.find((s) =>
        s.createdAt.startsWith(todayStr)
      )

      if (todaySession) {
        setActiveSessionId(todaySession.id)
      } else {
        // 今日无会话，自动创建
        const session = await storeCreateSession()
        setSessions((prev) => [session, ...prev])
        setActiveSessionId(session.id)
      }
    } finally {
      setIsLoading(false)
    }
  }, [])

  const renameSession = useCallback(async (id: number, newTitle: string) => {
    await updateSessionTitle(id, newTitle)
    await updateSessionFields(id, { titleAutoGenerated: false })
    setSessions((prev) =>
      prev.map((s) =>
        s.id === id ? { ...s, title: newTitle, titleAutoGenerated: false } : s
      )
    )
  }, [])

  const handleGenerateSummary = useCallback(
    (id: number) => {
      const session = sessions.find((s) => s.id === id)
      if (!session || session.summaryGenerated) {
        return
      }

      // 异步执行，不 await
      generateSessionSummary(id, session.title, session.titleAutoGenerated)
        .then((result) => {
          setSessions((prev) =>
            prev.map((s) =>
              s.id === id
                ? {
                    ...s,
                    summary: result.summary,
                    summaryGenerated: true,
                    ...(result.title ? { title: result.title } : {}),
                  }
                : s
            )
          )
        })
        .catch(() => {
          // 摘要生成失败，不自动重试
        })
    },
    [sessions]
  )

  return {
    sessions,
    activeSessionId,
    isLoading,
    switchSession,
    createSession: handleCreateSession,
    deleteSession: handleDeleteSession,
    loadTodayLastSession,
    renameSession,
    generateSummary: handleGenerateSummary,
  }
}
