/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/chatbot': typeof ChatbotRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/': typeof BooksIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books': typeof BooksIndexRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/chatbot': typeof ChatbotRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/': typeof BooksIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/chatbot'
    | '/customers'
    | '/dashboard'
    | '/settings'
    | '/books/$bookId'
    | '/books/'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chatbot'
    | '/dashboard'
    | '/settings'
    | '/books/$bookId'
    | '/books'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/chatbot'
    | '/customers'
    | '/dashboard'
    | '/settings'
    | '/books/$bookId'
    | '/books/'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRouteWithChildren
  ChatbotRoute: typeof ChatbotRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
  }
}

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface CustomersRouteChildren {
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRouteWithChildren,
  ChatbotRoute: ChatbotRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
