/**
 * 会话元数据存储
 * 通过 IPC 调用后端 CRUD，通过 tauri-plugin-fs 管理 JSONL 文件
 */

import { BaseDirectory, mkdir, remove } from '@tauri-apps/plugin-fs'

import { chat } from '@/api/commands/chat'

import type { Session, SectionSummary } from './types'

/**
 * 批量更新会话字段
 */
export const updateSessionFields = async (
  id: number,
  fields: {
    summary?: string
    titleAutoGenerated?: boolean
    summaryGenerated?: boolean
    title?: string
  }
): Promise<Session> => {
  const result = await chat.updateSessionFields(id, fields)
  if (result.isErr()) {
    throw new Error(result.error.toString())
  }
  return result.value
}

/**
 * 创建新会话
 * 同时在 appdata/sessions/ 下创建对应的文件夹
 */
export const createSession = async (title = '新对话'): Promise<Session> => {
  const session = await chat.createSession({ title }).then((r) => {
    if (r.isErr()) {
      throw new Error(r.error.toString())
    }
    return r.value
  })

  // 创建会话文件夹
  await mkdir(`sessions/session_${session.id}`, {
    baseDir: BaseDirectory.AppData,
    recursive: true,
  })

  return session
}

/**
 * 获取所有会话，按创建时间倒序
 */
export const getAllSessions = async (): Promise<Session[]> => {
  const result = await chat.getAllSessions()
  if (result.isErr()) {
    throw new Error(result.error.toString())
  }
  return result.value
}

/**
 * 根据 ID 获取会话
 */
export const getSessionById = async (id: number): Promise<Session | null> => {
  const result = await chat.getSession(id)
  if (result.isErr()) {
    throw new Error(result.error.toString())
  }
  return result.value
}

/**
 * 更新会话标题
 */
export const updateSessionTitle = async (
  id: number,
  title: string
): Promise<Session> => {
  const result = await chat.updateSessionTitle(id, title)
  if (result.isErr()) {
    throw new Error(result.error.toString())
  }
  return result.value
}

/**
 * 删除会话
 * 同时删除会话文件夹和 SQLite 数据
 */
export const deleteSession = async (id: number): Promise<void> => {
  // 删除会话文件夹
  try {
    await remove(`sessions/session_${id}`, {
      baseDir: BaseDirectory.AppData,
      recursive: true,
    })
  } catch {
    // 文件夹可能不存在，忽略错误
  }

  // 删除 SQLite 数据（级联删除节摘要）
  const result = await chat.deleteSession(id)
  if (result.isErr()) {
    throw new Error(result.error.toString())
  }
}

/**
 * 创建节摘要
 */
export const createSectionSummary = async (
  sessionId: number,
  sectionFile: string,
  summary: string,
  title?: string
): Promise<SectionSummary> => {
  const result = await chat.createSectionSummary(
    sessionId,
    sectionFile,
    title ?? null,
    summary
  )
  if (result.isErr()) {
    throw new Error(result.error.toString())
  }
  return result.value
}

/**
 * 获取指定会话的所有节摘要
 */
export const getSectionSummaries = async (
  sessionId: number
): Promise<SectionSummary[]> => {
  const result = await chat.getSectionSummaries(sessionId)
  if (result.isErr()) {
    throw new Error(result.error.toString())
  }
  return result.value
}

/**
 * 收集会话的所有 Section 摘要，调用 LLM 生成会话摘要和标题
 * 异步执行，不阻塞调用方
 */
export const generateSessionSummary = async (
  sessionId: number,
  sessionTitle: string,
  titleAutoGenerated: boolean
): Promise<{ summary: string; title?: string }> => {
  // 动态导入避免循环依赖
  const { generateText } = await import('ai')
  const { createZAiProvider, SUPPORTED_MODELS } = await import('@/ai/provider')

  // 收集该会话所有 Section 摘要
  const summaries = await getSectionSummaries(sessionId)
  if (summaries.length === 0) {
    return { summary: '暂无对话内容' }
  }

  const summaryTexts = summaries
    .map((s) => `- ${s.title ?? '无标题'}：${s.summary}`)
    .join('\n')

  const provider = createZAiProvider()
  if (provider.isErr()) {
    throw new Error(provider.error.toString())
  }

  const prompt = titleAutoGenerated
    ? `以下是一个会话中各节对话的摘要：
${summaryTexts}

请根据以上内容，生成一段简短的会话摘要（不超过50字）和一个简短的会话标题（不超过10字）。
请严格以 JSON 格式返回，不要包含其他内容：{ "title": "...", "summary": "..." }`
    : `以下是一个会话中各节对话的摘要：
${summaryTexts}

请根据以上内容，生成一段简短的会话摘要（不超过50字）。
请严格以 JSON 格式返回，不要包含其他内容：{ "summary": "..." }`

  const result = await generateText({
    model: provider.value.languageModel(SUPPORTED_MODELS.FAST),
    prompt,
  })

  const text = result.text.trim()
  const jsonMatch = text.match(/\{[\s\S]*\}/)
  if (!jsonMatch) {
    throw new Error('LLM 返回格式无法解析')
  }

  const parsed = JSON.parse(jsonMatch[0])
  const generatedSummary = String(parsed.summary ?? '').slice(0, 80)
  const generatedTitle = titleAutoGenerated
    ? String(parsed.title ?? '').slice(0, 15)
    : undefined

  // 更新数据库
  await updateSessionFields(sessionId, {
    summary: generatedSummary,
    summaryGenerated: true,
    ...(generatedTitle ? { title: generatedTitle } : {}),
  })

  return {
    summary: generatedSummary,
    title: generatedTitle,
  }
}
